stages:
  - deploy

cache:
  paths:
    - node_modules/

deploy-t1:
  stage: deploy
  script:
    - docker-compose up --force-recreate -d --build
    - docker image prune -f
  only:
    - master
  tags:
    - t1
